//
//  SongsMock.swift
//
//  Copyright © 2019 Alberto Saltarelli. All rights reserved.
//

public enum TimeSignature: CustomStringConvertible {
    
    case twoFour, threeFour, fourFour
    
    public var description: String {
        switch self {
            case .twoFour: return "2:4"
            case .threeFour: return "3:4"
            case .fourFour: return "4:4"
        }
    }
}

public enum Song: UInt8 {
    
    case americanAnthem, bolero, canonInD, eineKleineNachtmusik
    
    public var timeSignature: TimeSignature {
        switch self {
            case .americanAnthem, .bolero: return .threeFour
            case .canonInD, .eineKleineNachtmusik: return .fourFour
        }
    }
    
    public var notes: [Note] {
        
        switch self {
            case .americanAnthem:
                return [Note(duration: .eighth, frequency: .F4, dots: 1),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .quarter, frequency: .B3, accidental: .flat),
                        Note(duration: .quarter, frequency: .D4),
                        Note(duration: .quarter, frequency: .F4),
                        Note(duration: .half, frequency: .B4, accidental: .flat),
                        Note(duration: .eighth, frequency: .D5, dots: 1),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .D4),
                        Note(duration: .quarter, frequency: .E4),
                        Note(duration: .half, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .quarter, frequency: .D5, dots: 1),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .half, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4, dots: 1),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .F4),
                        Note(duration: .quarter, frequency: .D4),
                        Note(duration: .quarter, frequency: .B3, accidental: .flat),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5, accidental: .sharp),
                        Note(duration: .quarter, frequency: .D5),
                        Note(duration: .quarter, frequency: .E5, accidental: .flat),
                        Note(duration: .quarter, frequency: .F5),
                        Note(duration: .half, frequency: .F5),
                        Note(duration: .eighth, frequency: .E5, accidental: .flat),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .quarter, frequency: .C5),
                        Note(duration: .quarter, frequency: .D5),
                        Note(duration: .quarter, frequency: .E5, accidental: .flat),
                        Note(duration: .half, frequency: .E5, accidental: .flat),
                        Note(duration: .quarter, frequency: .E5, accidental: .flat),
                        Note(duration: .quarter, frequency: .D5, dots: 1),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .half, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4, dots: 1),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .D4),
                        Note(duration: .quarter, frequency: .E4),
                        Note(duration: .half, frequency: .F4),
                        Note(duration: .quarter, frequency: .F4),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .eighth, frequency: .B4, accidental: .flat),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .quarter, frequency: .G4),
                        Note(duration: .quarter, frequency: .G4),
                        Note(duration: .quarter, frequency: .G4),
                        Note(duration: .quarter, frequency: .C5),
                        Note(duration: .eighth, frequency: .E5, accidental: .flat),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat),
                        Note(duration: .quarter, frequency: .A4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .quarter, frequency: .B4, accidental: .flat, dots: 1),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .E5, accidental: .flat),
                        Note(duration: .half, frequency: .F5),
                        Note(duration: .eighth, frequency: .B4, accidental: .flat),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .quarter, frequency: .D5, dots: 1),
                        Note(duration: .eighth, frequency: .E5, accidental: .flat),
                        Note(duration: .quarter, frequency: .C5),
                        Note(duration: .half, frequency: .B4, accidental: .flat, dots: 1)]
            
            case .bolero:
                return [Note(duration: .quarter, frequency: .C5, dots: 1),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .D5),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .quarter, frequency: .C5, dots: 1),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .half, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .half, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .quarter, frequency: .C4),
                        Note(duration: .sixteenth, frequency: .C4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .quarter, frequency: .D4),
                        Note(duration: .half, frequency: .G4),
                        Note(duration: .half, frequency: .G4, dots: 1),
                        Note(duration: .quarter, frequency: .D5),
                        Note(duration: .eighth, frequency: .D5, dots: 1),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .D5),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .eighth, frequency: .B4, dots: 1),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .eighth, frequency: .F4, dots: 1),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .eighth, frequency: .G4, accidental: .flat),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .C4),
                        Note(duration: .quarter, frequency: .D4, dots: 1),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .C4),
                        Note(duration: .quarter, frequency: .D4, dots: 1),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .C4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .half, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .F4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .half, frequency: .C4, dots: 1)]
            
            case .canonInD:
                return [Note(duration: .half, frequency: .D5),
                        Note(duration: .half, frequency: .A4),
                        Note(duration: .half, frequency: .B4),
                        Note(duration: .half, frequency: .F4, accidental: .sharp),
                        Note(duration: .half, frequency: .G4),
                        Note(duration: .half, frequency: .D4),
                        Note(duration: .half, frequency: .G4),
                        Note(duration: .half, frequency: .A4),
                        Note(duration: .half, frequency: .F5, accidental: .sharp),
                        Note(duration: .half, frequency: .E5),
                        Note(duration: .half, frequency: .D5),
                        Note(duration: .half, frequency: .C5, accidental: .sharp),
                        Note(duration: .half, frequency: .B4),
                        Note(duration: .half, frequency: .A4),
                        Note(duration: .half, frequency: .B4),
                        Note(duration: .half, frequency: .C5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .C4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .F5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .A5),
                        Note(duration: .eighth, frequency: .B5),
                        Note(duration: .eighth, frequency: .G5),
                        Note(duration: .eighth, frequency: .F5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E5),
                        Note(duration: .eighth, frequency: .G5),
                        Note(duration: .eighth, frequency: .F5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E5),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .B3),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .C5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5, accidental: .sharp),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .A5),
                        Note(duration: .sixteenth, frequency: .F5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G5),
                        Note(duration: .eighth, frequency: .A5),
                        Note(duration: .sixteenth, frequency: .F5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G5),
                        Note(duration: .sixteenth, frequency: .A5),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .C5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .D5),
                        Note(duration: .sixteenth, frequency: .E5),
                        Note(duration: .sixteenth, frequency: .F5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G5),
                        Note(duration: .eighth, frequency: .F5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .D5),
                        Note(duration: .sixteenth, frequency: .E5),
                        Note(duration: .eighth, frequency: .F5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .D4),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .C5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .D5),
                        Note(duration: .sixteenth, frequency: .C5, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .F5, accidental: .sharp),
                        Note(duration: .half, frequency: .F5, accidental: .sharp),
                        Note(duration: .half, frequency: .E5),
                        Note(duration: .half, frequency: .D5, accidental: .sharp),
                        Note(duration: .half, frequency: .C5, accidental: .sharp),
                        Note(duration: .half, frequency: .B4),
                        Note(duration: .half, frequency: .A4),
                        Note(duration: .half, frequency: .B4),
                        Note(duration: .half, frequency: .C5, accidental: .sharp),
                        Note(duration: .whole, frequency: .D5),]
            
            case .eineKleineNachtmusik:
                return [Note(duration: .quarter, frequency: .G4, dots: 1),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .quarter, frequency: .G4, dots: 1),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .D4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .half, frequency: .D5),
                        Note(duration: .quarter, frequency: .C5, dots: 1),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .quarter, frequency: .C5, dots: 1),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .half, frequency: .D4, accidental: .sharp),
                        Note(duration: .quarter, frequency: .G4),
                        Note(duration: .quarter, frequency: .G4, dots: 1),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .quarter, frequency: .F4, accidental: .sharp, dots: 1),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .quarter, frequency: .G4, dots: 1),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .quarter, frequency: .F4, accidental: .sharp, dots: 1),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .sixteenth, frequency: .E4),
                        Note(duration: .sixteenth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .sixteenth, frequency: .G4),
                        Note(duration: .sixteenth, frequency: .A4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .D5),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .sixteenth, frequency: .B4),
                        Note(duration: .sixteenth, frequency: .C5),
                        Note(duration: .half, frequency: .D5),
                        Note(duration: .half, frequency: .D5),
                        Note(duration: .half, frequency: .E5),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .B4, accidental: .flat),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .quarter, frequency: .G4),
                        Note(duration: .quarter, frequency: .A4),
                        Note(duration: .half, frequency: .B4),
                        Note(duration: .half, frequency: .D5),
                        Note(duration: .half, frequency: .E5),
                        Note(duration: .eighth, frequency: .D5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .C5),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .B4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .A4),
                        Note(duration: .eighth, frequency: .G4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .eighth, frequency: .E4),
                        Note(duration: .eighth, frequency: .F4, accidental: .sharp),
                        Note(duration: .whole, frequency: .G4)]
        }
    }
}
